trigger: none

pool:
  name: student-lab-pool

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
    displayName: "Use Python 3.12"

  - script: |
      python -m pip install --upgrade pip
      pip install pytest requests
    displayName: "Install dependencies"

  - script: |
      pytest -s tests/smoke_tests.py --junitxml=smoke-results.xml
    displayName: "Run full smoke test suite"

  - task: PublishTestResults@2
    condition: always()   
    inputs:
      testResultsFiles: 'smoke-results.xml'
      testRunTitle: 'Post-deployment Smoke Test'
      failTaskOnFailedTests: true